### ISSUE TITLE
Not an issue just a question.

### ISSUE THREAD

**Issue by wsman217** [RypoFalem/The-Blue#2]
Hey so I found your GitHub through your ArmorStandEditor on Spigot. I have been looking through your GitHub for a bit and have just been really astounded at some of the plugins you have made. I think I am going to compile some of them with a few touches of my own and add them to my server. But I noticed that you didn't have many of the plugins uploaded to Spigot and I was wondering why because they seem to be really cool plugins. I also noticed that I couldn't find your Spigot account. What's up with that?

**Comment by RypoFalem** [comment]
Many of the plugins are unfinished, just me playing around with a concept. Many of those that work (or did work, I haven't tested them in years) require certain unpublished plugins from the server I used to be a part of as dependencies. Many of those dependencies I imagine are no longer maintained.

I'm not sure why you can't find my spigot account. It should be accessible from the armorstand editor page.
